version: "3"
services:
  mongo:
    image: mongo:6.0
    container_name: survivor_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: survivor
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
